//! `cargo test`-visible proof that the conformance-runner engine is green over the current
//! `dmtap-core/vectors.json` (the VERIFICATION GATE for this crate). Also locks the current,
//! honestly-reported suite.json coverage numbers so any change (new vectors, a dmtap-core fix
//! that closes one of the known self-contained gaps, a suite.json catalog update) is *noticed*
//! here rather than silently drifting.

use std::collections::BTreeMap;
use std::path::PathBuf;

use conformance_runner::{
    check_all_vectors, load_suite, load_vectors, run_all_suite_cases, spec_repo_dir, CaseOutcome,
    SuiteFile, VectorFile, Verdict,
};

/// The known-answer vectors. THE SPEC REPO OWNS THESE.
///
/// This used to be `CARGO_MANIFEST_DIR/vectors.json` — a THIRD copy of the vector set, alongside
/// the spec repo's `conformance/vectors/vectors.json` and the reference crate's own mirror of it.
/// Three copies is two too many, and they had already diverged in a way that hid a real defect:
/// the local copy still carried the pre-fix `safety_number` shape (`ik_a_hex`/`ik_b_hex`, the bare
/// identity key), so this runner and its private vectors agreed with each other while disagreeing
/// with the specification. A vector file a runner ships next to itself cannot falsify that runner.
///
/// Vectors belong with the spec; runners belong with implementations. The local copy is deleted and
/// this reads the spec repo's canonical file. There is no `exists()` fallback on purpose: if the
/// spec repo is not checked out, the mandatory gate must FAIL, not skip — `all_vectors_pass` is
/// this crate's whole charter.
fn vectors_path() -> PathBuf {
    spec_repo_dir().join("conformance/vectors/vectors.json")
}

fn suite_path() -> PathBuf {
    spec_repo_dir().join("conformance/suite.json")
}

/// The DMTAP-PUB (§22) / CAD-profile (§23) known-answer vectors live in a SEPARATE file in the
/// sibling spec repo (`pub_vectors.json`), generated by `gen_pub_vectors.py` and independently
/// cross-checked by `verify_pub_vectors.py` — NOT by the dmtap-core reference crate's `vectors.json`.
/// The runner recomputes them via `dmtap_core::pubobj`, so a passing run proves the Rust reference
/// reproduces the Python reference byte-for-byte.
fn pub_vectors_path() -> PathBuf {
    spec_repo_dir().join("conformance/vectors/pub_vectors.json")
}

/// Load `vectors.json` and, when the sibling spec repo is present, merge in `pub_vectors.json`.
/// Returns the combined vector set and a name→verdict map covering both. Used by every suite
/// cross-reference test so the §22/§23 cases resolve their `pub_*` vectors exactly as the core cases
/// resolve theirs.
fn load_merged() -> (VectorFile, BTreeMap<String, Verdict>) {
    let mut vf = load_vectors(&vectors_path()).expect("vectors.json must load");
    let mut results: BTreeMap<String, Verdict> = check_all_vectors(&vf).into_iter().collect();
    let pvp = pub_vectors_path();
    if pvp.exists() {
        let pvf = load_vectors(&pvp).expect("pub_vectors.json must load");
        for (name, verdict) in check_all_vectors(&pvf) {
            results.insert(name, verdict);
        }
        vf.vectors.extend(pvf.vectors);
    }
    (vf, results)
}

/// The mandatory gate: every vector in the committed `vectors.json` passes (reproduces from the
/// reference; every `cbor_*` vector canonically round-trips).
#[test]
fn all_vectors_pass() {
    let vf = load_vectors(&vectors_path()).expect("vectors.json must load");
    assert!(!vf.vectors.is_empty(), "vectors.json must not be empty");
    let results = check_all_vectors(&vf);
    let failures: Vec<String> = results
        .iter()
        .filter_map(|(name, v)| match v {
            Verdict::Fail(e) => Some(format!("{name}: {e}")),
            _ => None,
        })
        .collect();
    assert!(failures.is_empty(), "conformance-runner found FAILing vectors:\n{}", failures.join("\n"));
}

/// The DMTAP-PUB / CAD gate: every vector in the sibling spec repo's `pub_vectors.json` must
/// reproduce from `dmtap_core::pubobj` (skipped as a soft dependency if the sibling repo is absent).
/// This is the executable proof that §22 is implemented and matches the spec's independent reference.
#[test]
fn all_pub_vectors_pass() {
    let pvp = pub_vectors_path();
    if !pvp.exists() {
        eprintln!("skipping: sibling spec repo pub_vectors.json not found at {}", pvp.display());
        return;
    }
    let pvf = load_vectors(&pvp).expect("pub_vectors.json must load");
    assert!(!pvf.vectors.is_empty(), "pub_vectors.json must not be empty");
    let failures: Vec<String> = check_all_vectors(&pvf)
        .iter()
        .filter_map(|(name, v)| match v {
            Verdict::Fail(e) => Some(format!("{name}: {e}")),
            _ => None,
        })
        .collect();
    assert!(failures.is_empty(), "conformance-runner found FAILing DMTAP-PUB vectors:\n{}", failures.join("\n"));
}

/// Every `cbor_*` vector this crate recognizes by `input.type` gets the stronger typed check
/// (not just the generic canonical round-trip) — i.e. no vector silently falls back to
/// `PassGeneric` without us knowing. If this starts failing, either a new cbor_* vector type
/// appeared (extend `check_cbor_encode_vector`) or a dispatch regressed.
#[test]
fn every_known_cbor_type_gets_the_typed_check() {
    let vf = load_vectors(&vectors_path()).expect("vectors.json must load");
    let results = check_all_vectors(&vf);
    let generic_only: Vec<&str> = results
        .iter()
        .filter(|(_, v)| matches!(v, Verdict::PassGeneric))
        .map(|(n, _)| n.as_str())
        .collect();
    assert!(
        generic_only.is_empty(),
        "these cbor_* vectors only got the generic round-trip check (no `input.type` or unrecognized type): {generic_only:?}"
    );
}

/// Cross-reference the sibling spec repo's conformance-suite catalog, when checked out next to
/// this worktree (`../../../dmtap`). This is a soft dependency: if the sibling repo is absent
/// (e.g. a CI checkout of only this repo), the test is skipped rather than failing — the
/// mandatory proof is `all_vectors_pass` above, not this cross-reference.
#[test]
fn suite_json_cross_reference_matches_known_state() {
    let sp = suite_path();
    if !sp.exists() {
        eprintln!("skipping: sibling spec repo not found at {}", sp.display());
        return;
    }
    let (vf, results) = load_merged();
    let suite = load_suite(&sp).expect("suite.json must parse");
    let outcomes = run_all_suite_cases(&suite, &vf, &results);

    let mut pass = 0usize;
    let mut skip = 0usize;
    let mut fails: Vec<(String, String)> = Vec::new();
    for (id, outcome) in &outcomes {
        match outcome {
            CaseOutcome::Pass => pass += 1,
            CaseOutcome::Skipped(_) => skip += 1,
            CaseOutcome::Fail(reason) => fails.push((id.clone(), reason.clone())),
        }
    }

    // GAPS CLOSED: dmtap-core's low-level `cbor::decode` now enforces the full §18.1.1 canonical
    // ruleset on input — shortest-form integers/lengths, definite-length only, strictly ascending
    // map-key order (by encoded bytes), no duplicates — so the three previously-failing
    // self-contained MUST-reject cases (DMTAP-CBOR-05/06/07) now correctly REJECT and pass.
    //
    // The former spec-repo stale reference is now resolved: the sibling spec repo regenerated
    // `DMTAP-SUITE-02` to a reserved-suite `suite_accept_0x03` decode (0x03 is a registered reserved
    // code point — AES-256-GCM AEAD-diverse PQ-hybrid, §1.1/§21.15 — that DECODES as a known id but
    // fails closed on *use*) and added `DMTAP-SUITE-07`/`suite_reject_0x04` for the still-
    // unregistered 0x04, matching this crate's `vectors.json`.
    //
    // GAPS CLOSED (2026-07-19): §22 DMTAP-PUB is now implemented in `dmtap_core::pubobj` (public
    // manifests, pub_announce, author feeds, anti-rollback/equivocation), and this runner recomputes
    // every `pub_*` known-answer vector from `pub_vectors.json` via `load_merged()`. All 12
    // previously-failing `vectored` PUB cases now PASS, and the construction-todo PUB cases 09/10/11/
    // 12/17/18/19/20 are executed via `construction.rs`. The §23 CAD-profile checks (CAD-01..11) are
    // executed via `cad_profile_check` against `dmtap_core::pubobj::cad`; the 1 `manual-attestation`
    // case (PUB-21, the §22.7 client-UX MUST) stays a status skip. The DMTAP-PUB / CAD gap set is
    // therefore EMPTY.
    let expected_gap_ids: Vec<&str> = vec![];
    let actual_gap_ids: Vec<&str> = fails.iter().map(|(id, _)| id.as_str()).collect();
    let mut sorted_actual = actual_gap_ids.clone();
    sorted_actual.sort_unstable();
    let mut sorted_expected = expected_gap_ids.clone();
    sorted_expected.sort_unstable();
    assert_eq!(
        sorted_actual, sorted_expected,
        "suite.json known-gap set changed — investigate (either a regression, or a gap this \
         expectation needs updating for). Full failure detail: {fails:?}"
    );

    // Coverage floor, honestly stated. The catalog is 367 cases as of 2026-07-28 (it was 124 when
    // the sentence this replaces was written, and 104 before that — the old "116/124" claim had
    // gone stale by a factor of three, which is why a *count* now guards it instead of a comment).
    // This crate executes 182 of them and 185 come back `Skipped` with a printed reason, for
    // behaviour no crate in this workspace can exercise yet (see the `skip_reason` table in
    // `construction.rs`). The TOTAL is deliberately not pinned — every new spec case would break
    // that — but the EXECUTED count is a floor: the catalog growing can only add skips, so this
    // number falling means real coverage was lost.
    assert_eq!(pass + skip + fails.len(), outcomes.len());
    assert!(skip > 0, "expected at least some construction-todo cases to be skipped-with-note");
    assert!(
        pass >= 182,
        "executed suite.json coverage FELL to {pass} (was 182 at 2026-07-28) — real coverage was \
         lost, or cases were removed from the catalog. {skip} skipped, {} failed.",
        fails.len()
    );
}

/// No silent coverage gaps: EVERY case marked `status: "vectored"` in `suite.json` MUST actually
/// be executed (Pass or Fail), never `Skipped`. Structurally `run_vectored_case` never returns
/// `Skipped`, but this is a dedicated regression test so a future refactor that accidentally
/// routes a vectored case through the skip path is caught immediately, not discovered later as a
/// silently-inflated coverage number.
#[test]
fn every_vectored_case_is_actually_executed() {
    let sp = suite_path();
    if !sp.exists() {
        eprintln!("skipping: sibling spec repo not found at {}", sp.display());
        return;
    }
    let (vf, results) = load_merged();
    let suite = load_suite(&sp).expect("suite.json must parse");
    let outcomes = run_all_suite_cases(&suite, &vf, &results);

    let vectored_ids: std::collections::BTreeSet<&str> = suite
        .cases
        .iter()
        .filter(|c| c.status == "vectored")
        .map(|c| c.id.as_str())
        .collect();
    assert!(!vectored_ids.is_empty(), "expected at least one `vectored` case in suite.json");

    let silently_skipped: Vec<&str> = outcomes
        .iter()
        .filter(|(id, outcome)| {
            vectored_ids.contains(id.as_str()) && matches!(outcome, CaseOutcome::Skipped(_))
        })
        .map(|(id, _)| id.as_str())
        .collect();
    assert!(
        silently_skipped.is_empty(),
        "these `vectored` cases were SKIPPED instead of executed (coverage gap): {silently_skipped:?}"
    );
}

/// Regression guard for the catalog's SECOND vector-reference spelling.
///
/// `conformance/README.md` step 2 makes `vector` and `reuses_vector` equivalent for a runner ("If
/// the case has a `vector` (or `reuses_vector`), load that entry from `vectors.json`"), and
/// SUITE.md's `DMTAP-NAME-05` row spells it out: "reuses `keyname_key_ones` /
/// `keyname_key_twos`". This crate's suite reader honoured only `vector`, so that case reported
/// `status=vectored but no `vector` field` — a phantom coverage gap in a case that is in fact
/// fully byte-backed. This test pins the fix in both directions: the spelling must resolve, and
/// the cases using it must actually execute.
#[test]
fn cases_that_name_vectors_via_reuses_vector_are_executed() {
    let sp = suite_path();
    if !sp.exists() {
        eprintln!(
            "SKIPPED (loudly): {} is absent, so NOTHING about the sibling KOTVA catalog was \
             verified here — not the `reuses_vector` spelling, not DMTAP-NAME-05's key-name \
             inequality. CI must check KOTVA out beside this repo (see .github/workflows/ci.yml).",
            sp.display()
        );
        return;
    }
    let (vf, results) = load_merged();
    let suite = load_suite(&sp).expect("suite.json must parse");
    let outcomes: BTreeMap<String, CaseOutcome> =
        run_all_suite_cases(&suite, &vf, &results).into_iter().collect();

    // Coverage count, not a vacuous loop: the catalog must still contain cases using this
    // spelling. If it stops doing so, this guard has nothing to prove and says so.
    let reusing: Vec<&str> =
        suite.cases.iter().filter(|c| c.reuses_vector.is_some()).map(|c| c.id.as_str()).collect();
    assert!(
        reusing.len() >= 4,
        "expected >=4 `reuses_vector` cases in suite.json (DMTAP-PRE-05/NAME-05/VAL-02/VAL-08 at \
         the time of writing), found {}: {reusing:?}",
        reusing.len()
    );

    // Every case naming its vectors ONLY via `reuses_vector` must still resolve them — no case may
    // come back with the "no vector field" schema complaint.
    let unresolved: Vec<(&str, &str)> = suite
        .cases
        .iter()
        .filter(|c| c.vector.is_none() && c.reuses_vector.is_some())
        .filter_map(|c| match outcomes.get(&c.id) {
            Some(CaseOutcome::Fail(why)) if why.contains("no `vector` field") || why.contains("`reuses_vector` field") => {
                Some((c.id.as_str(), why.as_str()))
            }
            _ => None,
        })
        .collect();
    assert!(
        unresolved.is_empty(),
        "these cases name vectors via `reuses_vector` and the runner failed to resolve them: \
         {unresolved:#?}"
    );

    // And the one such case that is `status: vectored` — the §3.9.6/§18.9.17 distinct-names MUST —
    // must PASS, having actually compared two different committed key-names.
    let name05 = outcomes.get("DMTAP-NAME-05").expect("DMTAP-NAME-05 must exist in suite.json");
    assert_eq!(
        *name05,
        CaseOutcome::Pass,
        "DMTAP-NAME-05 (keyname_distinct over keyname_key_ones/keyname_key_twos) must execute and \
         pass, got {name05:?}"
    );
}

// ------------------------------------------------------------------------------------------
// Synthetic proof that the `keyname_distinct` check FAILS CLOSED.
//
// The three tests above can only show the real catalog passing. Passing is also what a check that
// asserts nothing produces, which is exactly the bug this file previously carried: the
// name-inequality assertion sat behind un-elsed `if let`/`if` guards, so a case that named its
// vectors under `reuses_vector`, or named the wrong number of them, sailed through as Pass. These
// tests feed the engine hand-built catalogs where the MUST is VIOLATED or unverifiable and require
// a Fail. They need no sibling repo, so they run in a bare checkout too.
// ------------------------------------------------------------------------------------------

fn synthetic(case: serde_json::Value, name_a: &str, name_b: &str) -> CaseOutcome {
    let suite: SuiteFile =
        serde_json::from_value(serde_json::json!({ "format": "t", "cases": [case] })).unwrap();
    let vectors: VectorFile = serde_json::from_value(serde_json::json!({
        "format": "t", "suite": "t", "generated_by": "t", "methodology": "t",
        "vectors": [
            { "name": "kn_a", "operation": "keyname_encode", "input": {}, "expected": { "name": name_a } },
            { "name": "kn_b", "operation": "keyname_encode", "input": {}, "expected": { "name": name_b } },
        ],
    }))
    .unwrap();
    let results: BTreeMap<String, Verdict> =
        [("kn_a".to_string(), Verdict::Pass), ("kn_b".to_string(), Verdict::Pass)].into();
    run_all_suite_cases(&suite, &vectors, &results).remove(0).1
}

fn keyname_case(vector_field: &str, value: serde_json::Value) -> serde_json::Value {
    let mut case = serde_json::json!({
        "id": "SYNTH-01", "level": "Core", "category": "NAME", "req": "MUST",
        "checks": "distinct keys yield distinct names", "operation": "keyname_distinct",
        "expect": { "outcome": "accept" }, "status": "vectored",
    });
    if !vector_field.is_empty() {
        case[vector_field] = value;
    }
    case
}

#[test]
fn keyname_distinct_fails_when_the_two_names_are_equal() {
    for field in ["vector", "reuses_vector"] {
        let outcome = synthetic(
            keyname_case(field, serde_json::json!(["kn_a", "kn_b"])),
            "same-name",
            "same-name",
        );
        match outcome {
            CaseOutcome::Fail(why) => assert!(
                why.contains("SAME name"),
                "expected the name-collision failure via `{field}`, got: {why}"
            ),
            other => panic!(
                "two IDENTICAL key-names must FAIL DMTAP-NAME-05 when named via `{field}`, got {other:?}"
            ),
        }
    }
}

#[test]
fn keyname_distinct_fails_closed_when_it_cannot_run() {
    // No vector reference at all under either spelling.
    match synthetic(keyname_case("", serde_json::Value::Null), "a", "b") {
        CaseOutcome::Fail(why) => assert!(why.contains("no vectors") || why.contains("neither")),
        other => panic!("a keyname_distinct case naming no vectors must FAIL, got {other:?}"),
    }
    // Wrong arity — one name, so there is nothing to compare.
    match synthetic(keyname_case("vector", serde_json::json!("kn_a")), "a", "b") {
        CaseOutcome::Fail(why) => assert!(
            why.contains("exactly 2 vector"),
            "expected an arity failure, got: {why}"
        ),
        other => panic!("a 1-vector keyname_distinct case must FAIL, got {other:?}"),
    }
    // A referenced vector that is missing from vectors.json: the names cannot be read.
    match synthetic(keyname_case("reuses_vector", serde_json::json!(["kn_a", "kn_missing"])), "a", "b") {
        CaseOutcome::Fail(_) => {}
        other => panic!("an unresolvable vector reference must FAIL, got {other:?}"),
    }
}

/// Regression guard for task item 3 (construction-todo cases): a meaningful number of them must
/// be ACTUALLY EXECUTED (Pass/Fail) against dmtap-core, not just uniformly skipped. This pins a
/// floor so a future change that reverts `construction::run_construction_case` back to "skip
/// everything" is caught here rather than silently shrinking real coverage.
#[test]
fn a_meaningful_share_of_construction_todo_cases_are_executed() {
    let sp = suite_path();
    if !sp.exists() {
        eprintln!("skipping: sibling spec repo not found at {}", sp.display());
        return;
    }
    let (vf, results) = load_merged();
    let suite = load_suite(&sp).expect("suite.json must parse");
    let outcomes = run_all_suite_cases(&suite, &vf, &results);

    let construction_todo_ids: std::collections::BTreeSet<&str> = suite
        .cases
        .iter()
        .filter(|c| c.status == "construction-todo")
        .map(|c| c.id.as_str())
        .collect();
    assert!(!construction_todo_ids.is_empty(), "expected at least one construction-todo case");

    let executed: Vec<&str> = outcomes
        .iter()
        .filter(|(id, outcome)| {
            construction_todo_ids.contains(id.as_str()) && !matches!(outcome, CaseOutcome::Skipped(_))
        })
        .map(|(id, _)| id.as_str())
        .collect();
    let failed: Vec<&str> = outcomes
        .iter()
        .filter(|(id, outcome)| {
            construction_todo_ids.contains(id.as_str()) && matches!(outcome, CaseOutcome::Fail(_))
        })
        .map(|(id, _)| id.as_str())
        .collect();
    assert!(
        failed.is_empty(),
        "construction-todo cases FAILED their construction (not just skipped): {failed:?}"
    );
    assert!(
        executed.len() >= 65,
        "expected at least 65 construction-todo cases to be actually executed (against dmtap-core \
         directly, plus more via dmtap-auth/dmtap-naming/dmtap-deniable/dmtap-mls/dmtap-clustersync \
         — see the Cargo.toml comment; this floor dropped from 77 to 65 when the 12 legacy-SMTP- \
         gateway cases (DMTAP-GWALIAS-*/DMTAP-GWATT-*/DMTAP-GWNAME-*/DMTAP-LEG-*) were removed \
         along with `envoir-gateway`, which moved out of this repo to the Ephor broker repo), got \
         {} ({executed:?}) — did construction::run_construction_case regress?",
        executed.len()
    );
}
